name: Build & Test Docker Image

on:
  pull_request:
    branches:
      - "main"

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ github.repository}}

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker Image
        run: docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest .

      - name: Test Docker Image
        run: docker run -d -p 8080:80 ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
