name: Build & Push Docker Image

on:
  pull_request:
    branches:
      - "main"

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ github.repository}}

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker Image
        run: docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest .

      - name: Test Docker Image
        run: docker run -d -p 8080:80 ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

  push-to-registry:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/quyenpqwork/whatsup-fe:latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: "{{defaultContext}}"
          push: true
          tags: |
            ${{ env.REGISTRY }}/quyenpqwork/whatsup-fe:${{ github.sha }}
            ${{ env.REGISTRY }}/quyenpqwork/whatsup-fe:latest
          labels: ${{ steps.meta.outputs.labels }}
